### ISSUE TITLE
Nth power and root Functions

### ISSUE THREAD

**Issue by imsiddhant07** [pccoeacm/all-calc#11]
# Todo

- Create a file for the Nth power and root calculator function

- (x)^n = (x * x * x * x... x * x * x) n times
- (x)^(1/n) = Nth root for x

# Example 

> (7)^4 =  7 * 7 * 7 * 7 = 2401
>(216)^(1/3) = 6

# Important

- **Guidelines for adding new functions are clearly mentioned in the [contributing guidelines](https://github.com/pccoeacm/all-calc/blob/main/CONTRIBUTING.md).**

- Screenshots of the output needs to be added along with the PRs for quicker merges.

- If any queries, discuss it in the issue thread.

**Comment by siddhantjain07** [comment]
Can I work on these functions

**Comment by Rohan1904** [comment]
Can i work on this ??? @tejasmorkar @SuyashSonawane

**Comment by karthi-01** [comment]
Can i work on this problem? @tejasmorkar

**Comment by Manas-K-Patil** [comment]
Can i work on this problem ?

**Comment by Rohan1904** [comment]
Should i start ??  @tejasmorkar @SuyashSonawane

**Comment by tejasmorkar** [comment]
@siddhantjain07 do you want to work on this issue?

**Comment by Manas-K-Patil** [comment]
yes sir

**Comment by imsiddhant07** [comment]
> @siddhantjain07 do you want to work on this issue?

no i only created an issue for others to solve, its okay if this is assigned to someone else

**Comment by tejasmorkar** [comment]
@Rohan1904 you can start working on it 👍

**Comment by Ganesh0403** [comment]
@tejasmorkar I think this issue is same like Exponent power.
