### ISSUE TITLE
Permutation and Combination Function

### ISSUE THREAD

**Issue by atharvamaid** [pccoeacm/all-calc#15]
# Todo

- Create a file for the permutation and combination calculator function

- comb( n, k) - will return the no of ways to choose k from n i.e  ( n! / (k! * (n – k)!) )
- perm(n,k) - will return all permutation of n and k i,e  ( n! / (n-k) ! ) 

# Example 

>comb(4 , 2) = 6
>perm(4, 2) = 12

# Important

- **Guidelines for adding new functions are clearly mentioned in the [contributing guidelines](https://github.com/pccoeacm/all-calc/blob/main/CONTRIBUTING.md).**

- Screenshots of the output needs to be added along with the PRs for quicker merges.

- If any queries, discuss it in the issue thread.

**Comment by atharvamaid** [comment]
Assign this issue to me

**Comment by atharvamaid** [comment]
@tejasmorkar  and @SuyashSonawane

**Comment by tejasmorkar** [comment]
Okay you can work on it 👍
