### ISSUE TITLE
Fibonacci Function

### ISSUE THREAD

**Issue by sanketchaudhari10** [pccoeacm/all-calc#25]
# Todo

- Create a file for the Fibonacci calculator function
- It takes a number denoting number of terms to  consider
-  Returns the value for the  Fibonacci operation

# Example 

input : 9
output : 34

# Important

- **Guidelines for adding new functions are clearly mentioned in the [contributing guidelines](https://github.com/pccoeacm/all-calc/blob/main/CONTRIBUTING.md).**

- Screenshots of the output needs to be added along with the PRs for quicker merges.

- If any queries, discuss it in the issue thread.

**Comment by sanketchaudhari10** [comment]
Should I work on this?

**Comment by tejasmorkar** [comment]
Sure you can go ahead @sanketchaudhari10
