### ISSUE TITLE
HCF Function

### ISSUE THREAD

**Issue by NityamKhandelwal1302** [pccoeacm/all-calc#32]
# Todo

- Create a file for the HCF calculator function

-the user will give two inputs and the function will find out all the factors of the inputs and return the highest common factor of the input

# Example 

> if 8 and 12 are input
factors of 8 are 2,4,8
factors of 12 are 2,4,6,12
so the output will be 4

# Important

- **Guidelines for adding new functions are clearly mentioned in the [contributing guidelines](https://github.com/pccoeacm/all-calc/blob/main/CONTRIBUTING.md).**

- Screenshots of the output needs to be added along with the PRs for quicker merges.

- If any queries, discuss it in the issue thread.

**Comment by NityamKhandelwal1302** [comment]
can i work on this

**Comment by tejasmorkar** [comment]
Okay sure 👍

**Comment by MEHUL25** [comment]
Hey this one is done. It is same as GCD (greatest common divisor) .

**Comment by tejasmorkar** [comment]
> Hey this one is done. It is same as GCD (greatest common divisor) .

Thanks for mentioning.

**Comment by tejasmorkar** [comment]
@NityamKhandelwal1302 could you check the issue #17 

Let me know about it.

**Comment by NityamKhandelwal1302** [comment]
@tejasmorkar  ya its the same so will look for other issue

**Comment by Manas-K-Patil** [comment]
yes gcd and hcf is the same

**Comment by tejasmorkar** [comment]
Okay, I'll close the issue now.
