### ISSUE TITLE
Average

### ISSUE THREAD

**Issue by Anand76666** [pccoeacm/all-calc#47]
# Todo

- Create a file for the ${Average} calculator function

- ${The average of given no}

# Example 

> ${6+4/2 =5}

# Important

- **Guidelines for adding new functions are clearly mentioned in the [contributing guidelines](https://github.com/pccoeacm/all-calc/blob/main/CONTRIBUTING.md).**

- Screenshots of the output needs to be added along with the PRs for quicker merges.

- If any queries, discuss it in the issue thread.
![Screenshot (71)](https://user-images.githubusercontent.com/65952263/94989440-7f0f3800-0592-11eb-8419-7c4e6ccd980c.png)

**Comment by Anand76666** [comment]
can i work on it

**Comment by tejasmorkar** [comment]
This issue is already mentioned under #40
