### ISSUE TITLE
Profit Loss Calculation

### ISSUE THREAD

**Issue by jferns19** [pccoeacm/all-calc#58]
# Todo

- To find whether there is profit or loss 

# Example 

>Input:  CP = 1500 ; SP = 2000
Output: 500 Profit

# Important

- **Guidelines for adding new functions are clearly mentioned in the [contributing guidelines](https://github.com/pccoeacm/all-calc/blob/main/CONTRIBUTING.md).**

- Screenshots of the output needs to be added along with the PRs for quicker merges.

- If any queries, discuss it in the issue thread.

**Comment by jferns19** [comment]
Can I work on this?

**Comment by tan1404may** [comment]
can i work on this??
