### ISSUE TITLE
Sigmoid Function

### ISSUE THREAD

**Issue by SuyashSonawane** [pccoeacm/all-calc#7]
# Todo

- Create a file for the Sigmoid calculator function

- Implement the following function
![image](https://user-images.githubusercontent.com/35629339/94983964-de565380-0564-11eb-9242-9001d48f6d6d.png)

# Example 

> Input -> 0 , Output -> 0.5

# Important

- **Guidelines for adding new functions are clearly mentioned in the [contributing guidelines](https://github.com/pccoeacm/all-calc/blob/main/CONTRIBUTING.md).**

- Screenshots of the output needs to be added along with the PRs for quicker merges.

- If any queries, discuss it in the issue thread.

**Comment by SuyashSonawane** [comment]
Hey, can I contribute?

**Comment by tejasmorkar** [comment]
Yes, sure @SuyashSonawane ! 🎉

**Comment by SuyashSonawane** [comment]
Ok I'm working

**Comment by pbuggaveeti28** [comment]
Hey, Can I work on this?
