### ISSUE TITLE
Polygon Internal Angle Calculator Function

### ISSUE THREAD

**Issue by jrakshit749** [pccoeacm/all-calc#82]
# Todo

- Create a file for the Polygon Internal Angle Calculator function

- The function will calculate the internal angles for the provided number of sides.

# Example 

> Input >> 5
> Output >> 72 

# Important

- **Guidelines for adding new functions are clearly mentioned in the [contributing guidelines](https://github.com/pccoeacm/all-calc/blob/main/CONTRIBUTING.md).**

- Screenshots of the output needs to be added along with the PRs for quicker merges.

- If any queries, discuss it in the issue thread.

**Comment by Apoorva-Datir** [comment]
can I work on this please??

**Comment by tejasmorkar** [comment]
This issue is opened by @jrakshit749 so if he wants to work on it, he can mention it or else it'll be assigned to you @Apoorva-Datir

**Comment by jrakshit749** [comment]
I'll work on it @tejasmorkar
