### ISSUE TITLE
Reciprocal Calculator Function

### ISSUE THREAD

**Issue by jrakshit749** [pccoeacm/all-calc#91]
# Todo

- Create a file for the Reciprocal calculator function

- This function will calculate the reciprocal of the given number.
# Example 

> Input> 2
>Output>0.5

# Important

- **Guidelines for adding new functions are clearly mentioned in the [contributing guidelines](https://github.com/pccoeacm/all-calc/blob/main/CONTRIBUTING.md).**

- Screenshots of the output needs to be added along with the PRs for quicker merges.

- If any queries, discuss it in the issue thread.

**Comment by jrakshit749** [comment]
Assign this to me please @tejasmorkar @SuyashSonawane

**Comment by Apoorva-Datir** [comment]
can I contribute please??
