### ISSUE TITLE
Root Mean Square Function

### ISSUE THREAD

**Issue by jrakshit749** [pccoeacm/all-calc#93]
# Todo

- Create a file for the Root Mean Square calculator function

- It will calculate the root mean square of the given list of numbers.

# Example 

> Input > 1 2 3
>Output> 2.160

# Important

- **Guidelines for adding new functions are clearly mentioned in the [contributing guidelines](https://github.com/pccoeacm/all-calc/blob/main/CONTRIBUTING.md).**

- Screenshots of the output needs to be added along with the PRs for quicker merges.

- If any queries, discuss it in the issue thread.

**Comment by Apoorva-Datir** [comment]
can I contribute please?

**Comment by jrakshit749** [comment]
@tejasmorkar @SuyashSonawane  Please assign this to me

**Comment by Apoorva-Datir** [comment]
I'll start working on it !
